#server.port=8080
#spring.application.name=springcloud-010-goods-portal
#eureka.instance.lease-renewal-interval-in-seconds=2
#eureka.instance.lease-expiration-duration-in-seconds=10
#eureka.instance.prefer-ip-address=true
#eureka.instance.instance-id=springclous-010-goods-portal
#eureka.client.service-url.defaultZone=http://eureka8761:8761/eureka,http://eureka8762:8762/eureka,http://eureka8763:8763/eureka
#feign.circuitbreaker.enabled=true
server:
  port: 8080
spring:
  application:
    name: springcloud-010-goods-portal
eureka:
  instance:
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 10
    instance-id: springcloud-010-goods-portal
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka8761:8761/eureka,http://eureka8762:8762/eureka,http://eureka8763:8763/eureka
feign:
  circuitbreaker:
    enabled: true
